name: secrets scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: "*"

jobs:
  TruffleHog:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
        with:
              fetch-depth: 0
      - name: TruffleHog secrets scanning
      - uses: trufflesecurity/trufflehog@main
        with:
            path: /
            base: main
            extra_args: --debug --only-verified


